#!/usr/bin/env bun
// Builds standalone macOS binaries with the web UI embedded.
// Usage: bun scripts/build-bin.ts [version]   → dist/ckanban-darwin-arm64, dist/ckanban-darwin-x64
import { readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative } from "node:path";

const root = join(import.meta.dir, "..");
const version = (process.argv[2] ?? process.env.CKANBAN_VERSION ?? "dev").replace(/^v/, "");
const genFile = join(root, "src/server/web-assets.gen.ts");
const STUB = `// Replaced by scripts/build-bin.ts when compiling the standalone binary; empty in dev (UI served from web/dist).
export const WEB_ASSETS: Record<string, string> = {};
`;

async function sh(cmd: string[], cwd = root) {
  const p = Bun.spawn(cmd, { cwd, stdout: "inherit", stderr: "inherit" });
  if ((await p.exited) !== 0) throw new Error(`failed: ${cmd.join(" ")}`);
}

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

await sh(["bun", "install", "--frozen-lockfile"], join(root, "web"));
await sh(["bun", "run", "build"], join(root, "web"));

const dist = join(root, "web/dist");
const files = walk(dist);
const lines = ["// GENERATED by scripts/build-bin.ts — do not edit or commit."];
const entries: string[] = [];
files.forEach((f, i) => {
  lines.push(`import f${i} from ${JSON.stringify(relative(join(root, "src/server"), f))} with { type: "file" };`);
  entries.push(`  ${JSON.stringify("/" + relative(dist, f))}: f${i},`);
});
lines.push("export const WEB_ASSETS: Record<string, string> = {", ...entries, "};", "");
writeFileSync(genFile, lines.join("\n"));

mkdirSync(join(root, "dist"), { recursive: true });
try {
  for (const arch of ["arm64", "x64"]) {
    const out = join(root, "dist", `ckanban-darwin-${arch}`);
    await sh([
      "bun", "build", "--compile", "--minify", `--target=bun-darwin-${arch}`,
      "--define", `CKANBAN_VERSION=${JSON.stringify(version)}`,
      "src/cli.ts", "--outfile", out,
    ]);
    console.log(`built ${relative(root, out)} (v${version})`);
  }
} finally {
  writeFileSync(genFile, STUB);
}
